### ISSUE TITLE
there is no screen to be resumed matching playit.gg message

### ISSUE THREAD

**Issue by EagleDTW** [aBoredDev/playit-setup-script#11]
**Describe the bug**
there is no screen to be resumed matching playit.gg message

**To Reproduce**
1. installed standard script install command get this error message when typing screen -r playit.gg*

**Expected behavior**
screen terminal showing playit startup screen.

**Screenshots**

**Desktop (please complete the following information):**
 - Distro: Raspbian 64-bit Bullseye
 - Version Bullseye
 - Nukkit server
 - Playit-0.9.3-armv7 install on RPI cm4

**Additional context**

**Comment by aBoredDev** [comment]
The cause of this is probably that playit didn't start properly for whatever reason.  Also, the script wouldn't have installed 0.9.3 by itself, because it's hard-coded to install 0.4.6, and that's because I haven't updated the version recently - there isn't a convenient way to get the latest version, or at least there wasn't until Did you manually install a more recent version?

**Comment by aBoredDev** [comment]
@EagleDTW Can you try it again with the most recent version of the script?

**Comment by EagleDTW** [comment]
Not entirely sure if I used the script again or went a slightly different route, but got playit.gg working on the pi! Should I need to install cycle again I’ll let you know if I encounter a similar error. Thank you for pushing the most recent version into the script!!
